theme = "lynx"
title = "Batako Studio"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Batako"
  headline = "現実を見ろ！俺たちには仮想現実（バーチャル）しかないんだぞ！"
  image = "author.png"
  links = [
    { link = { href = "https://github.com/batako", text = "GitHub", icon = "github" } },
    { instagram = "https://www.instagram.com/batakox/" },
    { x = "https://x.com/batakox" },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
